/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package viewer;

import controller.GerInterGrafica;
import java.awt.BorderLayout;

/**
 *
 * @author joaoh
 */
public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());
    private final GerInterGrafica gerInterGrafica;

    /**
     * Creates new form FrmPrincipal
     */
    public Dashboard() {
        this(GerInterGrafica.getInstance());
    }

    public Dashboard(GerInterGrafica gerInterGrafica) {
        this.gerInterGrafica = gerInterGrafica;
        initComponents();
        content.setLayout(new BorderLayout());
        exibirPainel(new Panelinicio(gerInterGrafica.getGerenciadorDominio()));
    }

    public void exibirPainel(javax.swing.JPanel painel) {
        painel.setSize(760, 690);
        painel.setLocation(0, 0);
        content.removeAll();
        content.add(painel, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        ButaoPaciente = new javax.swing.JButton();
        ButaoInicio = new javax.swing.JButton();
        ButaoAnamnese = new javax.swing.JButton();
        ButaoProntuario = new javax.swing.JButton();
        ButaoOdontograma = new javax.swing.JButton();
        ButaOrcamento = new javax.swing.JButton();
        ButaoConsentimento1 = new javax.swing.JButton();
        ButaoRelatoriosGerenciais = new javax.swing.JButton();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(82, 113, 255));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Icone NetBeans.png"))); // NOI18N

        ButaoPaciente.setBackground(new java.awt.Color(82, 113, 255));
        ButaoPaciente.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        ButaoPaciente.setForeground(new java.awt.Color(255, 255, 255));
        ButaoPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/users-alt.png"))); // NOI18N
        ButaoPaciente.setText("Pacientes");
        ButaoPaciente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ButaoPaciente.addActionListener(this::ButaoPacienteActionPerformed);

        ButaoInicio.setBackground(new java.awt.Color(82, 113, 255));
        ButaoInicio.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        ButaoInicio.setForeground(new java.awt.Color(255, 255, 255));
        ButaoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/home.png"))); // NOI18N
        ButaoInicio.setText("Inicio");
        ButaoInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ButaoInicio.addActionListener(this::ButaoInicioActionPerformed);

        ButaoAnamnese.setBackground(new java.awt.Color(82, 113, 255));
        ButaoAnamnese.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        ButaoAnamnese.setForeground(new java.awt.Color(255, 255, 255));
        ButaoAnamnese.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ballot.png"))); // NOI18N
        ButaoAnamnese.setText("Anamnese");
        ButaoAnamnese.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ButaoAnamnese.addActionListener(this::ButaoAnamneseActionPerformed);

        ButaoProntuario.setBackground(new java.awt.Color(82, 113, 255));
        ButaoProntuario.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        ButaoProntuario.setForeground(new java.awt.Color(255, 255, 255));
        ButaoProntuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/clipboard-user.png"))); // NOI18N
        ButaoProntuario.setText("Prontuários");
        ButaoProntuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ButaoProntuario.addActionListener(this::ButaoProntuarioActionPerformed);

        ButaoOdontograma.setBackground(new java.awt.Color(82, 113, 255));
        ButaoOdontograma.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        ButaoOdontograma.setForeground(new java.awt.Color(255, 255, 255));
        ButaoOdontograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/tooth.png"))); // NOI18N
        ButaoOdontograma.setText("Odontograma");
        ButaoOdontograma.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ButaoOdontograma.addActionListener(this::ButaoOdontogramaActionPerformed);

        ButaOrcamento.setBackground(new java.awt.Color(82, 113, 255));
        ButaOrcamento.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        ButaOrcamento.setForeground(new java.awt.Color(255, 255, 255));
        ButaOrcamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/checklist-task-budget.png"))); // NOI18N
        ButaOrcamento.setText("Orçamentos");
        ButaOrcamento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ButaOrcamento.addActionListener(this::ButaOrcamentoActionPerformed);

        ButaoConsentimento1.setBackground(new java.awt.Color(82, 113, 255));
        ButaoConsentimento1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        ButaoConsentimento1.setForeground(new java.awt.Color(255, 255, 255));
        ButaoConsentimento1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/scroll-document-story.png"))); // NOI18N
        ButaoConsentimento1.setText("Consentimentos");
        ButaoConsentimento1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ButaoConsentimento1.addActionListener(this::ButaoConsentimento1ActionPerformed);

        ButaoRelatoriosGerenciais.setBackground(new java.awt.Color(82, 113, 255));
        ButaoRelatoriosGerenciais.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        ButaoRelatoriosGerenciais.setForeground(new java.awt.Color(255, 255, 255));
        ButaoRelatoriosGerenciais.setText("Relatorios");
        ButaoRelatoriosGerenciais.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ButaoRelatoriosGerenciais.addActionListener(this::ButaoRelatoriosGerenciaisActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButaoPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButaoInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButaoAnamnese, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButaoProntuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButaoOdontograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButaoConsentimento1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButaOrcamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButaoRelatoriosGerenciais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(ButaoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButaoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButaoAnamnese, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButaoProntuario, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButaoOdontograma, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButaoConsentimento1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButaOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButaoRelatoriosGerenciais, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 759, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButaoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButaoPacienteActionPerformed
        gerInterGrafica.abrirPacientes();
    }//GEN-LAST:event_ButaoPacienteActionPerformed

    private void ButaoInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButaoInicioActionPerformed
        gerInterGrafica.abrirInicio();
    }//GEN-LAST:event_ButaoInicioActionPerformed

    private void ButaoAnamneseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButaoAnamneseActionPerformed
        gerInterGrafica.abrirAnamnese();
    }//GEN-LAST:event_ButaoAnamneseActionPerformed

    private void ButaoProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButaoProntuarioActionPerformed
        gerInterGrafica.abrirProntuario();
    }//GEN-LAST:event_ButaoProntuarioActionPerformed

    private void ButaoOdontogramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButaoOdontogramaActionPerformed
        gerInterGrafica.abrirOdontograma();
    }//GEN-LAST:event_ButaoOdontogramaActionPerformed

    private void ButaOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButaOrcamentoActionPerformed
        gerInterGrafica.abrirOrcamento();
    }//GEN-LAST:event_ButaOrcamentoActionPerformed

    private void ButaoConsentimento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButaoConsentimento1ActionPerformed
        gerInterGrafica.abrirConsentimento();
    }//GEN-LAST:event_ButaoConsentimento1ActionPerformed

    private void ButaoRelatoriosGerenciaisActionPerformed(java.awt.event.ActionEvent evt) {
        gerInterGrafica.abrirRelatoriosGerenciais(this);
    }

    /**
     * @param args the command line arguments
     */
    

    public static void main(String args[]) {
        /* Set a modern look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            javax.swing.UIManager.put("Button.arc", 10);
            javax.swing.UIManager.put("Component.arc", 10);
            javax.swing.UIManager.put("TextComponent.arc", 10);
            com.formdev.flatlaf.FlatLightLaf.setup();
        } catch (RuntimeException ex) {
            try {
                javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
            } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException fallbackEx) {
                logger.log(java.util.logging.Level.SEVERE, null, fallbackEx);
            }
        }
        //</editor-fold>

        /* Create and display the form */
        GerInterGrafica.getInstance().iniciar();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButaOrcamento;
    private javax.swing.JButton ButaoAnamnese;
    private javax.swing.JButton ButaoConsentimento1;
    private javax.swing.JButton ButaoInicio;
    private javax.swing.JButton ButaoOdontograma;
    private javax.swing.JButton ButaoPaciente;
    private javax.swing.JButton ButaoProntuario;
    private javax.swing.JButton ButaoRelatoriosGerenciais;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel content;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
