/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package viewer;

import controller.GerenciadorDominio;
import controller.GerInterGrafica;
import java.awt.Color;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.swing.AbstractAction;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import model.CondicaoDente;
import model.Dente;
import model.Odontograma;
import model.Paciente;

/**
 *
 * @author joaoh
 */
public class PanelOdontograma extends javax.swing.JPanel {

    /**
     * Creates new form PanelOdontograma
     */
    private final GerenciadorDominio gerenciador;
    private final Paciente pacienteInicial;
    private final Map<Integer, CondicaoDente> estadosDentes = new LinkedHashMap<>();
    private final Map<Integer, JButton> botoesDentes = new LinkedHashMap<>();
    private List<Paciente> pacientes = new ArrayList<>();
    private Odontograma odontogramaAtual;

    public PanelOdontograma() {
        this(GerInterGrafica.getInstance().getGerenciadorDominio());
    }

    public PanelOdontograma(GerenciadorDominio gerenciador) {
        this(gerenciador, null);
    }

    public PanelOdontograma(GerenciadorDominio gerenciador, Paciente pacienteInicial) {
        this.gerenciador = gerenciador;
        this.pacienteInicial = pacienteInicial;
        initComponents();
        configurarOdontograma();
        carregarPacientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        NomePaciente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        dente38 = new javax.swing.JButton();
        dente47 = new javax.swing.JButton();
        dente46 = new javax.swing.JButton();
        dente35 = new javax.swing.JButton();
        dente48 = new javax.swing.JButton();
        dente45 = new javax.swing.JButton();
        dente43 = new javax.swing.JButton();
        dente42 = new javax.swing.JButton();
        dente32 = new javax.swing.JButton();
        dente41 = new javax.swing.JButton();
        dente33 = new javax.swing.JButton();
        dente31 = new javax.swing.JButton();
        dente44 = new javax.swing.JButton();
        dente34 = new javax.swing.JButton();
        dente36 = new javax.swing.JButton();
        dente37 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        dente29 = new javax.swing.JButton();
        dente17 = new javax.swing.JButton();
        dente16 = new javax.swing.JButton();
        dente25 = new javax.swing.JButton();
        dente18 = new javax.swing.JButton();
        dente15 = new javax.swing.JButton();
        dente13 = new javax.swing.JButton();
        dente12 = new javax.swing.JButton();
        dente22 = new javax.swing.JButton();
        dente11 = new javax.swing.JButton();
        dente23 = new javax.swing.JButton();
        dente21 = new javax.swing.JButton();
        dente14 = new javax.swing.JButton();
        dente24 = new javax.swing.JButton();
        dente26 = new javax.swing.JButton();
        dente27 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel13 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        BotaoSalvarOdontograma = new javax.swing.JButton();
        BotaoRelatorioOdontograma = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(760, 690));
        setMinimumSize(new java.awt.Dimension(760, 690));
        setPreferredSize(new java.awt.Dimension(760, 690));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel1.setText("Odontograma");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel3.setText("Selecionar Paciente");

        jComboBox1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel4.setText("Paciente: ");

        NomePaciente.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        NomePaciente.setText("Nome Paciente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(NomePaciente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel2.setText("Acarda Superior");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel5.setText("Acarda Inferior");

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        dente38.setText("38");
        dente38.addActionListener(this::dente38ActionPerformed);

        dente47.setText("47");
        dente47.addActionListener(this::dente47ActionPerformed);

        dente46.setText("46");
        dente46.addActionListener(this::dente46ActionPerformed);

        dente35.setText("35");
        dente35.addActionListener(this::dente35ActionPerformed);

        dente48.setText("48");
        dente48.addActionListener(this::dente48ActionPerformed);

        dente45.setText("45");
        dente45.addActionListener(this::dente45ActionPerformed);

        dente43.setText("43");
        dente43.addActionListener(this::dente43ActionPerformed);

        dente42.setText("42");
        dente42.addActionListener(this::dente42ActionPerformed);

        dente32.setText("32");
        dente32.addActionListener(this::dente32ActionPerformed);

        dente41.setText("41");
        dente41.addActionListener(this::dente41ActionPerformed);

        dente33.setText("33");
        dente33.addActionListener(this::dente33ActionPerformed);

        dente31.setText("31");
        dente31.addActionListener(this::dente31ActionPerformed);

        dente44.setText("44");
        dente44.addActionListener(this::dente44ActionPerformed);

        dente34.setText("34");
        dente34.addActionListener(this::dente34ActionPerformed);

        dente36.setText("36");
        dente36.addActionListener(this::dente36ActionPerformed);

        dente37.setText("37");
        dente37.addActionListener(this::dente37ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(dente31, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dente32, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dente33, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dente34, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dente35, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dente36, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dente37, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dente38, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(dente48, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dente47, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dente46, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dente45, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dente44, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dente43, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dente42, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dente41, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dente41, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dente42, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dente43, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dente44, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dente45, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dente46, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dente47, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dente48, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dente38, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dente37, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dente36, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dente35, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dente34, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dente33, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dente32, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dente31, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));

        dente29.setText("29");
        dente29.addActionListener(this::dente29ActionPerformed);

        dente17.setText("17");
        dente17.addActionListener(this::dente17ActionPerformed);

        dente16.setText("16");
        dente16.addActionListener(this::dente16ActionPerformed);

        dente25.setText("25");
        dente25.addActionListener(this::dente25ActionPerformed);

        dente18.setText("18");
        dente18.addActionListener(this::dente18ActionPerformed);

        dente15.setText("15");
        dente15.addActionListener(this::dente15ActionPerformed);

        dente13.setText("13");
        dente13.addActionListener(this::dente13ActionPerformed);

        dente12.setText("12");
        dente12.addActionListener(this::dente12ActionPerformed);

        dente22.setText("22");
        dente22.addActionListener(this::dente22ActionPerformed);

        dente11.setText("11");
        dente11.addActionListener(this::dente11ActionPerformed);

        dente23.setText("23");
        dente23.addActionListener(this::dente23ActionPerformed);

        dente21.setText("21");
        dente21.addActionListener(this::dente21ActionPerformed);

        dente14.setText("14");
        dente14.addActionListener(this::dente14ActionPerformed);

        dente24.setText("24");
        dente24.addActionListener(this::dente24ActionPerformed);

        dente26.setText("26");
        dente26.addActionListener(this::dente26ActionPerformed);

        dente27.setText("27");
        dente27.addActionListener(this::dente27ActionPerformed);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(dente21, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dente22, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dente23, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dente24, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dente25, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dente26, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dente27, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dente29, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(dente18, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dente17, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dente16, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dente15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dente14, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dente13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dente12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dente11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dente11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dente12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dente13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dente14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dente15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dente16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dente17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dente18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dente29, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dente27, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dente26, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dente25, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dente24, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dente23, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dente22, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dente21, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setMaximumSize(new java.awt.Dimension(0, 308));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 308));

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 102));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        jPanel12.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Restaurado");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Mapa");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Careado");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Observaçao");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Concluído");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel12.setText("Dentes em manutenção");

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel13.setText("do paciente");

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 48)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("34");

        BotaoSalvarOdontograma.setBackground(new java.awt.Color(82, 113, 255));
        BotaoSalvarOdontograma.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        BotaoSalvarOdontograma.setForeground(new java.awt.Color(255, 255, 255));
        BotaoSalvarOdontograma.setText("Salvar Odontograma");
        BotaoSalvarOdontograma.addActionListener(e -> salvarOdontograma());

        BotaoRelatorioOdontograma.setBackground(new java.awt.Color(82, 113, 255));
        BotaoRelatorioOdontograma.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        BotaoRelatorioOdontograma.setForeground(new java.awt.Color(255, 255, 255));
        BotaoRelatorioOdontograma.setText("Relatorio");
        BotaoRelatorioOdontograma.addActionListener(e -> gerarRelatorioOdontograma());

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotaoSalvarOdontograma, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(BotaoRelatorioOdontograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoSalvarOdontograma, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoRelatorioOdontograma, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel11.setText("Observação:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(3, 3, 3)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dente37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dente37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dente37ActionPerformed

    private void dente36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dente36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dente36ActionPerformed

    private void dente34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dente34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dente34ActionPerformed

    private void dente44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dente44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dente44ActionPerformed

    private void dente31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dente31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dente31ActionPerformed

    private void dente33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dente33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dente33ActionPerformed

    private void dente41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dente41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dente41ActionPerformed

    private void dente32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dente32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dente32ActionPerformed

    private void dente42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dente42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dente42ActionPerformed

    private void dente43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dente43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dente43ActionPerformed

    private void dente45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dente45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dente45ActionPerformed

    private void dente48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dente48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dente48ActionPerformed

    private void dente35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dente35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dente35ActionPerformed

    private void dente46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dente46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dente46ActionPerformed

    private void dente47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dente47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dente47ActionPerformed

    private void dente38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dente38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dente38ActionPerformed

    private void dente29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dente29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dente29ActionPerformed

    private void dente17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dente17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dente17ActionPerformed

    private void dente16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dente16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dente16ActionPerformed

    private void dente25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dente25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dente25ActionPerformed

    private void dente18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dente18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dente18ActionPerformed

    private void dente15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dente15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dente15ActionPerformed

    private void dente13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dente13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dente13ActionPerformed

    private void dente12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dente12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dente12ActionPerformed

    private void dente22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dente22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dente22ActionPerformed

    private void dente11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dente11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dente11ActionPerformed

    private void dente23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dente23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dente23ActionPerformed

    private void dente21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dente21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dente21ActionPerformed

    private void dente14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dente14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dente14ActionPerformed

    private void dente24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dente24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dente24ActionPerformed

    private void dente26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dente26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dente26ActionPerformed

    private void dente27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dente27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dente27ActionPerformed



    private void configurarOdontograma() {
        jLabel2.setText("Arcada Superior");
        jLabel5.setText("Arcada Inferior");
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder("Observação do odontograma (Ctrl+S para salvar)"));
        dente29.setText("28");

        configurarDente(dente11, 11); configurarDente(dente12, 12); configurarDente(dente13, 13); configurarDente(dente14, 14);
        configurarDente(dente15, 15); configurarDente(dente16, 16); configurarDente(dente17, 17); configurarDente(dente18, 18);
        configurarDente(dente21, 21); configurarDente(dente22, 22); configurarDente(dente23, 23); configurarDente(dente24, 24);
        configurarDente(dente25, 25); configurarDente(dente26, 26); configurarDente(dente27, 27); configurarDente(dente29, 28);
        configurarDente(dente31, 31); configurarDente(dente32, 32); configurarDente(dente33, 33); configurarDente(dente34, 34);
        configurarDente(dente35, 35); configurarDente(dente36, 36); configurarDente(dente37, 37); configurarDente(dente38, 38);
        configurarDente(dente41, 41); configurarDente(dente42, 42); configurarDente(dente43, 43); configurarDente(dente44, 44);
        configurarDente(dente45, 45); configurarDente(dente46, 46); configurarDente(dente47, 47); configurarDente(dente48, 48);

        jTextArea1.getInputMap().put(KeyStroke.getKeyStroke("control S"), "salvarOdontograma");
        jTextArea1.getActionMap().put("salvarOdontograma", new AbstractAction() {
            @Override public void actionPerformed(java.awt.event.ActionEvent e) { salvarOdontograma(); }
        });
    }

    private void configurarDente(JButton botao, int numero) {
        estadosDentes.put(numero, CondicaoDente.NORMAL);
        botoesDentes.put(numero, botao);
        botao.putClientProperty("numeroDente", numero);
        botao.putClientProperty("estadoDente", CondicaoDente.NORMAL);
        botao.setOpaque(true);
        botao.setBackground(Color.WHITE);
        botao.setToolTipText("Dente " + numero + " - clique para alternar condição");
        botao.addActionListener(e -> alternarDente(botao, numero));
    }

    private void alternarDente(JButton botao, int numero) {
        CondicaoDente atual = (CondicaoDente) botao.getClientProperty("estadoDente");
        CondicaoDente proximo;
        switch (atual) {
            case NORMAL: proximo = CondicaoDente.RESTAURADO; break;
            case RESTAURADO: proximo = CondicaoDente.MANUTENCAO; break;
            case MANUTENCAO: proximo = CondicaoDente.CARIADO; break;
            case CARIADO: proximo = CondicaoDente.AUSENTE; break;
            default: proximo = CondicaoDente.NORMAL; break;
        }
        botao.putClientProperty("estadoDente", proximo);
        estadosDentes.put(numero, proximo);
        aplicarCor(botao, proximo);
        atualizarResumoDentes();
    }

    private void aplicarCor(JButton botao, CondicaoDente estado) {
        switch (estado) {
            case RESTAURADO: botao.setBackground(new Color(102, 204, 102)); break;
            case MANUTENCAO: botao.setBackground(new Color(255, 215, 0)); break;
            case CARIADO: botao.setBackground(new Color(255, 102, 102)); break;
            case AUSENTE: botao.setBackground(new Color(120, 120, 120)); break;
            default: botao.setBackground(Color.WHITE); break;
        }
    }

    private void carregarPacientes() {
        pacientes = gerenciador.listarPacientesSeguro();
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Selecione um paciente");
        for (Paciente p : pacientes) {
            jComboBox1.addItem(p.getNome());
        }
        jComboBox1.addActionListener(e -> atualizarNomePaciente());
        selecionarPacienteInicial();
        atualizarNomePaciente();
    }

    private void selecionarPacienteInicial() {
        if (pacienteInicial == null || pacienteInicial.getId() == null) {
            return;
        }
        for (int i = 0; i < pacientes.size(); i++) {
            if (pacienteInicial.getId().equals(pacientes.get(i).getId())) {
                jComboBox1.setSelectedIndex(i + 1);
                return;
            }
        }
    }

    private void atualizarNomePaciente() {
        int idx = jComboBox1.getSelectedIndex();
        if (idx <= 0 || idx - 1 >= pacientes.size()) {
            NomePaciente.setText("Nome Paciente");
            limparOdontograma();
        } else {
            Paciente paciente = pacientes.get(idx - 1);
            NomePaciente.setText(paciente.getNome());
            carregarOdontogramaAnterior(paciente);
        }
    }

    private void atualizarResumoDentes() {
        long alterados = estadosDentes.values().stream().filter(e -> e != CondicaoDente.NORMAL).count();
        jLabel14.setText(String.valueOf(alterados));
    }

    private void salvarOdontograma() {
        Paciente paciente = getPacienteSelecionado();
        if (paciente == null) {
            JOptionPane.showMessageDialog(this, "Selecione um paciente antes de salvar.");
            return;
        }
        try {
            odontogramaAtual = gerenciador.salvarOdontograma(paciente, estadosDentes, jTextArea1.getText());
            JOptionPane.showMessageDialog(this, "Odontograma salvo com sucesso.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro ao salvar odontograma", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void gerarRelatorioOdontograma() {
        Paciente paciente = getPacienteSelecionado();
        if (paciente == null) {
            JOptionPane.showMessageDialog(this, "Selecione um paciente.");
            return;
        }
        try {
            GerInterGrafica.getInstance().getGerRelatorios().relComLista(
                    gerenciador.listarOdontogramasPorPacienteParaRelatorio(paciente), "relOdontogramas");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro ao gerar relatorio", JOptionPane.ERROR_MESSAGE);
        }
    }

    private Paciente getPacienteSelecionado() {
        int idx = jComboBox1.getSelectedIndex();
        if (idx <= 0 || idx - 1 >= pacientes.size()) {
            return null;
        }
        return pacientes.get(idx - 1);
    }

    private void carregarOdontogramaAnterior(Paciente paciente) {
        try {
            Odontograma odontograma = gerenciador.buscarUltimoOdontogramaPaciente(paciente);
            limparOdontograma();
            if (odontograma == null) {
                odontogramaAtual = null;
                return;
            }
            odontogramaAtual = odontograma;
            jTextArea1.setText(odontograma.getObservacoes() == null ? "" : odontograma.getObservacoes());
            for (Dente dente : odontograma.getDentes()) {
                JButton botao = botoesDentes.get(dente.getNumero());
                if (botao != null) {
                    CondicaoDente condicao = dente.getCondicao() == null ? CondicaoDente.NORMAL : dente.getCondicao();
                    estadosDentes.put(dente.getNumero(), condicao);
                    botao.putClientProperty("estadoDente", condicao);
                    aplicarCor(botao, condicao);
                }
            }
            atualizarResumoDentes();
        } catch (Exception ex) {
            odontogramaAtual = null;
            limparOdontograma();
        }
    }

    private void limparOdontograma() {
        for (Map.Entry<Integer, JButton> entrada : botoesDentes.entrySet()) {
            estadosDentes.put(entrada.getKey(), CondicaoDente.NORMAL);
            entrada.getValue().putClientProperty("estadoDente", CondicaoDente.NORMAL);
            aplicarCor(entrada.getValue(), CondicaoDente.NORMAL);
        }
        jTextArea1.setText("");
        atualizarResumoDentes();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NomePaciente;
    private javax.swing.JButton BotaoRelatorioOdontograma;
    private javax.swing.JButton BotaoSalvarOdontograma;
    private javax.swing.JButton dente11;
    private javax.swing.JButton dente12;
    private javax.swing.JButton dente13;
    private javax.swing.JButton dente14;
    private javax.swing.JButton dente15;
    private javax.swing.JButton dente16;
    private javax.swing.JButton dente17;
    private javax.swing.JButton dente18;
    private javax.swing.JButton dente21;
    private javax.swing.JButton dente22;
    private javax.swing.JButton dente23;
    private javax.swing.JButton dente24;
    private javax.swing.JButton dente25;
    private javax.swing.JButton dente26;
    private javax.swing.JButton dente27;
    private javax.swing.JButton dente29;
    private javax.swing.JButton dente31;
    private javax.swing.JButton dente32;
    private javax.swing.JButton dente33;
    private javax.swing.JButton dente34;
    private javax.swing.JButton dente35;
    private javax.swing.JButton dente36;
    private javax.swing.JButton dente37;
    private javax.swing.JButton dente38;
    private javax.swing.JButton dente41;
    private javax.swing.JButton dente42;
    private javax.swing.JButton dente43;
    private javax.swing.JButton dente44;
    private javax.swing.JButton dente45;
    private javax.swing.JButton dente46;
    private javax.swing.JButton dente47;
    private javax.swing.JButton dente48;
    private javax.swing.JButton jButton100;
    private javax.swing.JButton jButton101;
    private javax.swing.JButton jButton102;
    private javax.swing.JButton jButton103;
    private javax.swing.JButton jButton104;
    private javax.swing.JButton jButton105;
    private javax.swing.JButton jButton106;
    private javax.swing.JButton jButton107;
    private javax.swing.JButton jButton108;
    private javax.swing.JButton jButton109;
    private javax.swing.JButton jButton110;
    private javax.swing.JButton jButton111;
    private javax.swing.JButton jButton112;
    private javax.swing.JButton jButton113;
    private javax.swing.JButton jButton114;
    private javax.swing.JButton jButton115;
    private javax.swing.JButton jButton116;
    private javax.swing.JButton jButton117;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton84;
    private javax.swing.JButton jButton85;
    private javax.swing.JButton jButton86;
    private javax.swing.JButton jButton87;
    private javax.swing.JButton jButton88;
    private javax.swing.JButton jButton89;
    private javax.swing.JButton jButton90;
    private javax.swing.JButton jButton91;
    private javax.swing.JButton jButton92;
    private javax.swing.JButton jButton93;
    private javax.swing.JButton jButton94;
    private javax.swing.JButton jButton95;
    private javax.swing.JButton jButton96;
    private javax.swing.JButton jButton97;
    private javax.swing.JButton jButton98;
    private javax.swing.JButton jButton99;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
