/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package viewer;

import controller.FuncoesUteis;
import controller.GerenciadorDominio;
import controller.GerInterGrafica;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Anamnese;
import model.Paciente;

/**
 *
 * @author joaoh
 */
public class PanelAnamnese extends javax.swing.JPanel {

    /**
     * Creates new form PanelAnamnese
     */
    private final GerenciadorDominio gerenciador;
    private final Paciente pacienteInicial;
    private List<Paciente> pacientes = new ArrayList<>();
    private Anamnese anamneseAtual;

    public PanelAnamnese() {
        this(GerInterGrafica.getInstance().getGerenciadorDominio());
    }

    public PanelAnamnese(GerenciadorDominio gerenciador) {
        this(gerenciador, null);
    }

    public PanelAnamnese(GerenciadorDominio gerenciador, Paciente pacienteInicial) {
        this.gerenciador = gerenciador;
        this.pacienteInicial = pacienteInicial;
        initComponents();
        configurarPainel();
        carregarPacientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFoto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SlecionarPaciente = new javax.swing.JComboBox<>();
        ComboBoxSexo = new javax.swing.JComboBox<>();
        txtFormaterCPF = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtFormaterDataNascimento = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtFormaterTelefone = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        TextoHDA = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TextoHFamiliar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TextoHPP = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TextoHFisiologica = new javax.swing.JTextField();
        BotaoSalvarAnamnese = new javax.swing.JButton();
        BotaoEditarAnamnese = new javax.swing.JButton();
        BotaoExcluirAnamnese = new javax.swing.JButton();
        BotaoRelatorioAnamnese = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(760, 690));
        setMinimumSize(new java.awt.Dimension(760, 690));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(760, 690));

        lblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoto.setText("Foto");
        lblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFotoMouseClicked(evt);
            }
        });

        ComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));

        try {
            txtFormaterCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFormaterCPF.setToolTipText("");

        jLabel1.setText("Nome");

        jLabel6.setText("Data de Nascimento");

        try {
            txtFormaterDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("CPF");

        jLabel3.setText("Sexo");

        jLabel14.setText("Telefone");

        try {
            txtFormaterTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel7.setText("História da Doença Atual (HDA)");

        TextoHDA.addActionListener(this::TextoHDAActionPerformed);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel8.setText("História Patológica Progressa");

        TextoHFamiliar.addActionListener(this::TextoHFamiliarActionPerformed);

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel9.setText("História Familiar");

        TextoHPP.addActionListener(this::TextoHPPActionPerformed);

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel10.setText("História Fisiológica");

        TextoHFisiologica.addActionListener(this::TextoHFisiologicaActionPerformed);

        BotaoSalvarAnamnese.setBackground(new java.awt.Color(82, 113, 255));
        BotaoSalvarAnamnese.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        BotaoSalvarAnamnese.setForeground(new java.awt.Color(255, 255, 255));
        BotaoSalvarAnamnese.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add-document.png"))); // NOI18N
        BotaoSalvarAnamnese.setText("Salvar");
        BotaoSalvarAnamnese.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        BotaoEditarAnamnese.setBackground(new java.awt.Color(82, 113, 255));
        BotaoEditarAnamnese.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        BotaoEditarAnamnese.setForeground(new java.awt.Color(255, 255, 255));
        BotaoEditarAnamnese.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pencil.png"))); // NOI18N
        BotaoEditarAnamnese.setText("Editar");
        BotaoEditarAnamnese.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        BotaoExcluirAnamnese.setBackground(new java.awt.Color(82, 113, 255));
        BotaoExcluirAnamnese.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        BotaoExcluirAnamnese.setForeground(new java.awt.Color(255, 255, 255));
        BotaoExcluirAnamnese.setText("Excluir");
        BotaoExcluirAnamnese.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        BotaoRelatorioAnamnese.setBackground(new java.awt.Color(82, 113, 255));
        BotaoRelatorioAnamnese.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        BotaoRelatorioAnamnese.setForeground(new java.awt.Color(255, 255, 255));
        BotaoRelatorioAnamnese.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/scroll-document-story.png"))); // NOI18N
        BotaoRelatorioAnamnese.setText("Relatorio");
        BotaoRelatorioAnamnese.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 359, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, TextoHFisiologica)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, TextoHPP)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, TextoHFamiliar)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, TextoHDA)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(SlecionarPaciente, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(18, 18, 18))
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                            .add(jLabel4)
                                            .add(jLabel1)
                                            .add(txtNome, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                                            .add(txtFormaterCPF))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 56, Short.MAX_VALUE)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                                .add(jLabel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .add(txtFormaterDataNascimento, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 107, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                            .add(jLabel3)
                                            .add(ComboBoxSexo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 107, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(73, 73, 73))
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabel14)
                                            .add(txtFormaterTelefone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 207, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .add(lblFoto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 161, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(15, 15, 15))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 359, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 359, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 359, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(0, 0, Short.MAX_VALUE))))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(BotaoSalvarAnamnese, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(BotaoEditarAnamnese, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(BotaoExcluirAnamnese, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(BotaoRelatorioAnamnese, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 170, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(jLabel5)
                    .add(0, 0, Short.MAX_VALUE)))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(jLabel2)
                    .add(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblFoto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 190, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(SlecionarPaciente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel1)
                            .add(jLabel3))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtNome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(ComboBoxSexo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel4)
                            .add(jLabel6))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtFormaterCPF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txtFormaterDataNascimento, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel14)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtFormaterTelefone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(TextoHDA, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(TextoHPP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 73, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(TextoHFisiologica, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 73, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(TextoHFamiliar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(BotaoSalvarAnamnese, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(BotaoEditarAnamnese, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(BotaoExcluirAnamnese, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(BotaoRelatorioAnamnese, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(jLabel5)
                    .add(0, 0, Short.MAX_VALUE)))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(jLabel2)
                    .add(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFotoMouseClicked

        JFileChooser janArq = new JFileChooser();

        janArq.setAcceptAllFileFilterUsed(false);

        janArq.setFileFilter(new FileNameExtensionFilter("Arquivo de imagem", "png", "jpg", "gif", "bmp"));

        if (janArq.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            File arq = janArq.getSelectedFile();
            ImageIcon imagem = new ImageIcon (arq.getAbsolutePath());
            lblFoto.setIcon(imagem);
            lblFoto.setText("");
            lblFoto.putClientProperty("caminhoFoto", arq.getAbsolutePath());
        }
    }//GEN-LAST:event_lblFotoMouseClicked

    private void TextoHDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoHDAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoHDAActionPerformed

    private void TextoHFamiliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoHFamiliarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoHFamiliarActionPerformed

    private void TextoHPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoHPPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoHPPActionPerformed

    private void TextoHFisiologicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoHFisiologicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoHFisiologicaActionPerformed



    private void configurarPainel() {
        SlecionarPaciente.addActionListener(e -> preencherPacienteSelecionado());
        TextoHFamiliar.setToolTipText("Pressione Ctrl+S para salvar a anamnese");
        BotaoSalvarAnamnese.addActionListener(e -> salvarAnamnese());
        BotaoEditarAnamnese.addActionListener(e -> editarAnamnese());
        BotaoExcluirAnamnese.addActionListener(e -> excluirAnamnese());
        BotaoRelatorioAnamnese.addActionListener(e -> gerarRelatorioAnamnese());
        BotaoSalvarAnamnese.setToolTipText("Salvar anamnese do paciente selecionado");
        BotaoEditarAnamnese.setToolTipText("Editar a anamnese carregada");
        BotaoExcluirAnamnese.setToolTipText("Excluir a anamnese carregada");
        BotaoRelatorioAnamnese.setToolTipText("Gerar relatorio de anamneses");
        TextoHDA.getInputMap().put(KeyStroke.getKeyStroke("control S"), "salvarAnamnese");
        TextoHPP.getInputMap().put(KeyStroke.getKeyStroke("control S"), "salvarAnamnese");
        TextoHFisiologica.getInputMap().put(KeyStroke.getKeyStroke("control S"), "salvarAnamnese");
        TextoHFamiliar.getInputMap().put(KeyStroke.getKeyStroke("control S"), "salvarAnamnese");
        AbstractAction salvar = new AbstractAction() {
            @Override public void actionPerformed(java.awt.event.ActionEvent e) { salvarAnamnese(); }
        };
        TextoHDA.getActionMap().put("salvarAnamnese", salvar);
        TextoHPP.getActionMap().put("salvarAnamnese", salvar);
        TextoHFisiologica.getActionMap().put("salvarAnamnese", salvar);
        TextoHFamiliar.getActionMap().put("salvarAnamnese", salvar);
        jLabel8.setText("História Patológica Pregressa");
    }

    private void carregarPacientes() {
        pacientes = gerenciador.listarPacientesSeguro();
        SlecionarPaciente.removeAllItems();
        SlecionarPaciente.addItem("Selecione um paciente");
        for (Paciente p : pacientes) {
            SlecionarPaciente.addItem(p.getNome());
        }
        selecionarPacienteInicial();
    }

    private void selecionarPacienteInicial() {
        if (pacienteInicial == null || pacienteInicial.getId() == null) {
            return;
        }
        for (int i = 0; i < pacientes.size(); i++) {
            if (pacienteInicial.getId().equals(pacientes.get(i).getId())) {
                SlecionarPaciente.setSelectedIndex(i + 1);
                return;
            }
        }
    }

    private Paciente getPacienteSelecionado() {
        int idx = SlecionarPaciente.getSelectedIndex();
        if (idx <= 0 || idx - 1 >= pacientes.size()) {
            return null;
        }
        return pacientes.get(idx - 1);
    }

    private void preencherPacienteSelecionado() {
        Paciente p = getPacienteSelecionado();
        if (p == null) {
            limparCamposAnamnese();
            return;
        }
        txtNome.setText(p.getNome());
        txtFormaterCPF.setText(p.getCpf());
        txtFormaterDataNascimento.setText(p.getDataNascimentoFormatada());
        txtFormaterTelefone.setText(p.getTelefone());
        ComboBoxSexo.setSelectedIndex(0);
        ImageIcon foto = FuncoesUteis.bytesToIcon(p.getFotoIdentificacao());
        if (foto != null) {
            FuncoesUteis.mostrarFoto(lblFoto, foto);
        }
        carregarAnamneseAnterior(p);
    }

    private void salvarAnamnese() {
        Paciente p = getPacienteSelecionado();
        if (p == null) {
            JOptionPane.showMessageDialog(this, "Selecione um paciente antes de salvar.");
            return;
        }
        try {
            if (System.currentTimeMillis() >= 0) {
                anamneseAtual = gerenciador.inserirAnamneseClinica(p, TextoHDA.getText(), TextoHPP.getText(),
                        TextoHFisiologica.getText(), TextoHFamiliar.getText());
                JOptionPane.showMessageDialog(this, "Anamnese salva com sucesso.");
                return;
            }
            String observacoes = "HDA: " + TextoHDA.getText() + "\n"
                    + "História fisiológica: " + TextoHFisiologica.getText() + "\n"
                    + "História familiar: " + TextoHFamiliar.getText();
            gerenciador.inserirAnamnese(p, false, "",
                    !TextoHFisiologica.getText().isBlank(), TextoHFisiologica.getText(),
                    !TextoHPP.getText().isBlank(), TextoHPP.getText(), observacoes);
            JOptionPane.showMessageDialog(this, "Anamnese salva com sucesso.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro ao salvar anamnese", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void editarAnamnese() {
        Paciente p = getPacienteSelecionado();
        if (p == null) {
            JOptionPane.showMessageDialog(this, "Selecione um paciente antes de editar.");
            return;
        }
        if (anamneseAtual == null) {
            JOptionPane.showMessageDialog(this, "Selecione uma anamnese para editar.");
            return;
        }
        try {
            anamneseAtual = gerenciador.alterarAnamneseClinica(anamneseAtual, p, TextoHDA.getText(), TextoHPP.getText(),
                    TextoHFisiologica.getText(), TextoHFamiliar.getText());
            JOptionPane.showMessageDialog(this, "Anamnese alterada com sucesso.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro ao editar anamnese", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void excluirAnamnese() {
        if (anamneseAtual == null) {
            JOptionPane.showMessageDialog(this, "Selecione um registro para excluir.");
            return;
        }
        int resposta = JOptionPane.showConfirmDialog(this,
                "Tem certeza que deseja excluir este registro?",
                "Excluir anamnese", JOptionPane.YES_NO_OPTION);
        if (resposta != JOptionPane.YES_OPTION) {
            return;
        }
        try {
            gerenciador.excluirAnamnese(anamneseAtual);
            anamneseAtual = null;
            limparCamposAnamnese();
            JOptionPane.showMessageDialog(this, "Registro excluido com sucesso.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro ao excluir anamnese", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void gerarRelatorioAnamnese() {
        try {
            Paciente paciente = getPacienteSelecionado();
            java.util.List<?> dados = paciente == null
                    ? gerenciador.listarAnamnesesParaRelatorio()
                    : gerenciador.listarAnamnesesPorPacienteParaRelatorio(paciente);
            GerInterGrafica.getInstance().getGerRelatorios().relComLista(dados, "relAnamneses");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro ao gerar relatorio", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void carregarAnamneseAnterior(Paciente paciente) {
        try {
            Anamnese anamnese = gerenciador.buscarUltimaAnamnesePaciente(paciente);
            if (anamnese == null) {
                anamneseAtual = null;
                limparCamposAnamnese();
                return;
            }
            anamneseAtual = anamnese;
            TextoHDA.setText(valor(anamnese.getHistoriaDoencaAtual(), anamnese.getObservacoes()));
            TextoHPP.setText(valor(anamnese.getHistoriaPatologicaPregressa(), anamnese.getDoencas()));
            TextoHFisiologica.setText(valor(anamnese.getHistoriaFisiologica(), anamnese.getMedicamentos()));
            TextoHFamiliar.setText(valor(anamnese.getHistoriaFamiliar(), anamnese.getAlergias()));
        } catch (Exception ex) {
            anamneseAtual = null;
            limparCamposAnamnese();
        }
    }

    private void limparCamposAnamnese() {
        TextoHDA.setText("");
        TextoHPP.setText("");
        TextoHFisiologica.setText("");
        TextoHFamiliar.setText("");
    }

    private String valor(String preferencial, String fallback) {
        return preferencial == null || preferencial.isBlank() ? (fallback == null ? "" : fallback) : preferencial;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoEditarAnamnese;
    private javax.swing.JButton BotaoExcluirAnamnese;
    private javax.swing.JButton BotaoRelatorioAnamnese;
    private javax.swing.JButton BotaoSalvarAnamnese;
    private javax.swing.JComboBox<String> ComboBoxSexo;
    private javax.swing.JComboBox<String> SlecionarPaciente;
    private javax.swing.JTextField TextoHDA;
    private javax.swing.JTextField TextoHFamiliar;
    private javax.swing.JTextField TextoHFisiologica;
    private javax.swing.JTextField TextoHPP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JFormattedTextField txtFormaterCPF;
    private javax.swing.JFormattedTextField txtFormaterDataNascimento;
    private javax.swing.JFormattedTextField txtFormaterTelefone;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
